name: removie
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  carousel_slider: ^4.0.0
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  jwt_decoder: ^2.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true  
